/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AvisoPrivacidadRouteImport } from './routes/aviso-privacidad'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNexusRouteImport } from './routes/_authenticated/nexus'
import { Route as AuthenticatedNexusIndexRouteImport } from './routes/_authenticated/nexus/index'
import { Route as AuthenticatedNexusWhatsappBridgeRouteImport } from './routes/_authenticated/nexus/whatsapp-bridge'
import { Route as AuthenticatedNexusTimelineRouteImport } from './routes/_authenticated/nexus/timeline'
import { Route as AuthenticatedNexusSupplyRouteImport } from './routes/_authenticated/nexus/supply'
import { Route as AuthenticatedNexusSettingsRouteImport } from './routes/_authenticated/nexus/settings'
import { Route as AuthenticatedNexusSecurityCenterRouteImport } from './routes/_authenticated/nexus/security-center'
import { Route as AuthenticatedNexusSecurityRouteImport } from './routes/_authenticated/nexus/security'
import { Route as AuthenticatedNexusSafetyRouteImport } from './routes/_authenticated/nexus/safety'
import { Route as AuthenticatedNexusReportsRouteImport } from './routes/_authenticated/nexus/reports'
import { Route as AuthenticatedNexusRecruitingEnterpriseRouteImport } from './routes/_authenticated/nexus/recruiting-enterprise'
import { Route as AuthenticatedNexusRecruitingRouteImport } from './routes/_authenticated/nexus/recruiting'
import { Route as AuthenticatedNexusQualityRouteImport } from './routes/_authenticated/nexus/quality'
import { Route as AuthenticatedNexusQaRouteImport } from './routes/_authenticated/nexus/qa'
import { Route as AuthenticatedNexusProjectsRouteImport } from './routes/_authenticated/nexus/projects'
import { Route as AuthenticatedNexusProductionRouteImport } from './routes/_authenticated/nexus/production'
import { Route as AuthenticatedNexusPlatformRouteImport } from './routes/_authenticated/nexus/platform'
import { Route as AuthenticatedNexusOperationsRouteImport } from './routes/_authenticated/nexus/operations'
import { Route as AuthenticatedNexusObservabilityRouteImport } from './routes/_authenticated/nexus/observability'
import { Route as AuthenticatedNexusMonitoringRouteImport } from './routes/_authenticated/nexus/monitoring'
import { Route as AuthenticatedNexusMailHubRouteImport } from './routes/_authenticated/nexus/mail-hub'
import { Route as AuthenticatedNexusIntelligenceRouteImport } from './routes/_authenticated/nexus/intelligence'
import { Route as AuthenticatedNexusHrRouteImport } from './routes/_authenticated/nexus/hr'
import { Route as AuthenticatedNexusFinanceRouteImport } from './routes/_authenticated/nexus/finance'
import { Route as AuthenticatedNexusCrmRouteImport } from './routes/_authenticated/nexus/crm'
import { Route as AuthenticatedNexusBillingRouteImport } from './routes/_authenticated/nexus/billing'
import { Route as AuthenticatedNexusApprovalsRouteImport } from './routes/_authenticated/nexus/approvals'
import { Route as AuthenticatedNexusAlertsRouteImport } from './routes/_authenticated/nexus/alerts'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicHooksInterviewRemindersRouteImport } from './routes/api/public/hooks/interview-reminders'
import { Route as AuthenticatedNexusProjectsProjectIdRouteImport } from './routes/_authenticated/nexus/projects.$projectId'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoPrivacidadRoute = AvisoPrivacidadRouteImport.update({
  id: '/aviso-privacidad',
  path: '/aviso-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNexusRoute = AuthenticatedNexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNexusIndexRoute = AuthenticatedNexusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedNexusRoute,
} as any)
const AuthenticatedNexusWhatsappBridgeRoute =
  AuthenticatedNexusWhatsappBridgeRouteImport.update({
    id: '/whatsapp-bridge',
    path: '/whatsapp-bridge',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusTimelineRoute =
  AuthenticatedNexusTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusSupplyRoute =
  AuthenticatedNexusSupplyRouteImport.update({
    id: '/supply',
    path: '/supply',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusSettingsRoute =
  AuthenticatedNexusSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusSecurityCenterRoute =
  AuthenticatedNexusSecurityCenterRouteImport.update({
    id: '/security-center',
    path: '/security-center',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusSecurityRoute =
  AuthenticatedNexusSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusSafetyRoute =
  AuthenticatedNexusSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusReportsRoute =
  AuthenticatedNexusReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusRecruitingEnterpriseRoute =
  AuthenticatedNexusRecruitingEnterpriseRouteImport.update({
    id: '/recruiting-enterprise',
    path: '/recruiting-enterprise',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusRecruitingRoute =
  AuthenticatedNexusRecruitingRouteImport.update({
    id: '/recruiting',
    path: '/recruiting',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusQualityRoute =
  AuthenticatedNexusQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusQaRoute = AuthenticatedNexusQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedNexusRoute,
} as any)
const AuthenticatedNexusProjectsRoute =
  AuthenticatedNexusProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusProductionRoute =
  AuthenticatedNexusProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusPlatformRoute =
  AuthenticatedNexusPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusOperationsRoute =
  AuthenticatedNexusOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusObservabilityRoute =
  AuthenticatedNexusObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusMonitoringRoute =
  AuthenticatedNexusMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusMailHubRoute =
  AuthenticatedNexusMailHubRouteImport.update({
    id: '/mail-hub',
    path: '/mail-hub',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusIntelligenceRoute =
  AuthenticatedNexusIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusHrRoute = AuthenticatedNexusHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedNexusRoute,
} as any)
const AuthenticatedNexusFinanceRoute =
  AuthenticatedNexusFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusCrmRoute = AuthenticatedNexusCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedNexusRoute,
} as any)
const AuthenticatedNexusBillingRoute =
  AuthenticatedNexusBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusApprovalsRoute =
  AuthenticatedNexusApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const AuthenticatedNexusAlertsRoute =
  AuthenticatedNexusAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedNexusRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInterviewRemindersRoute =
  ApiPublicHooksInterviewRemindersRouteImport.update({
    id: '/api/public/hooks/interview-reminders',
    path: '/api/public/hooks/interview-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNexusProjectsProjectIdRoute =
  AuthenticatedNexusProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedNexusProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-privacidad': typeof AvisoPrivacidadRoute
  '/cookies': typeof CookiesRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/nexus': typeof AuthenticatedNexusRouteWithChildren
  '/nexus/alerts': typeof AuthenticatedNexusAlertsRoute
  '/nexus/approvals': typeof AuthenticatedNexusApprovalsRoute
  '/nexus/billing': typeof AuthenticatedNexusBillingRoute
  '/nexus/crm': typeof AuthenticatedNexusCrmRoute
  '/nexus/finance': typeof AuthenticatedNexusFinanceRoute
  '/nexus/hr': typeof AuthenticatedNexusHrRoute
  '/nexus/intelligence': typeof AuthenticatedNexusIntelligenceRoute
  '/nexus/mail-hub': typeof AuthenticatedNexusMailHubRoute
  '/nexus/monitoring': typeof AuthenticatedNexusMonitoringRoute
  '/nexus/observability': typeof AuthenticatedNexusObservabilityRoute
  '/nexus/operations': typeof AuthenticatedNexusOperationsRoute
  '/nexus/platform': typeof AuthenticatedNexusPlatformRoute
  '/nexus/production': typeof AuthenticatedNexusProductionRoute
  '/nexus/projects': typeof AuthenticatedNexusProjectsRouteWithChildren
  '/nexus/qa': typeof AuthenticatedNexusQaRoute
  '/nexus/quality': typeof AuthenticatedNexusQualityRoute
  '/nexus/recruiting': typeof AuthenticatedNexusRecruitingRoute
  '/nexus/recruiting-enterprise': typeof AuthenticatedNexusRecruitingEnterpriseRoute
  '/nexus/reports': typeof AuthenticatedNexusReportsRoute
  '/nexus/safety': typeof AuthenticatedNexusSafetyRoute
  '/nexus/security': typeof AuthenticatedNexusSecurityRoute
  '/nexus/security-center': typeof AuthenticatedNexusSecurityCenterRoute
  '/nexus/settings': typeof AuthenticatedNexusSettingsRoute
  '/nexus/supply': typeof AuthenticatedNexusSupplyRoute
  '/nexus/timeline': typeof AuthenticatedNexusTimelineRoute
  '/nexus/whatsapp-bridge': typeof AuthenticatedNexusWhatsappBridgeRoute
  '/nexus/': typeof AuthenticatedNexusIndexRoute
  '/nexus/projects/$projectId': typeof AuthenticatedNexusProjectsProjectIdRoute
  '/api/public/hooks/interview-reminders': typeof ApiPublicHooksInterviewRemindersRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-privacidad': typeof AvisoPrivacidadRoute
  '/cookies': typeof CookiesRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/nexus/alerts': typeof AuthenticatedNexusAlertsRoute
  '/nexus/approvals': typeof AuthenticatedNexusApprovalsRoute
  '/nexus/billing': typeof AuthenticatedNexusBillingRoute
  '/nexus/crm': typeof AuthenticatedNexusCrmRoute
  '/nexus/finance': typeof AuthenticatedNexusFinanceRoute
  '/nexus/hr': typeof AuthenticatedNexusHrRoute
  '/nexus/intelligence': typeof AuthenticatedNexusIntelligenceRoute
  '/nexus/mail-hub': typeof AuthenticatedNexusMailHubRoute
  '/nexus/monitoring': typeof AuthenticatedNexusMonitoringRoute
  '/nexus/observability': typeof AuthenticatedNexusObservabilityRoute
  '/nexus/operations': typeof AuthenticatedNexusOperationsRoute
  '/nexus/platform': typeof AuthenticatedNexusPlatformRoute
  '/nexus/production': typeof AuthenticatedNexusProductionRoute
  '/nexus/projects': typeof AuthenticatedNexusProjectsRouteWithChildren
  '/nexus/qa': typeof AuthenticatedNexusQaRoute
  '/nexus/quality': typeof AuthenticatedNexusQualityRoute
  '/nexus/recruiting': typeof AuthenticatedNexusRecruitingRoute
  '/nexus/recruiting-enterprise': typeof AuthenticatedNexusRecruitingEnterpriseRoute
  '/nexus/reports': typeof AuthenticatedNexusReportsRoute
  '/nexus/safety': typeof AuthenticatedNexusSafetyRoute
  '/nexus/security': typeof AuthenticatedNexusSecurityRoute
  '/nexus/security-center': typeof AuthenticatedNexusSecurityCenterRoute
  '/nexus/settings': typeof AuthenticatedNexusSettingsRoute
  '/nexus/supply': typeof AuthenticatedNexusSupplyRoute
  '/nexus/timeline': typeof AuthenticatedNexusTimelineRoute
  '/nexus/whatsapp-bridge': typeof AuthenticatedNexusWhatsappBridgeRoute
  '/nexus': typeof AuthenticatedNexusIndexRoute
  '/nexus/projects/$projectId': typeof AuthenticatedNexusProjectsProjectIdRoute
  '/api/public/hooks/interview-reminders': typeof ApiPublicHooksInterviewRemindersRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aviso-privacidad': typeof AvisoPrivacidadRoute
  '/cookies': typeof CookiesRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/nexus': typeof AuthenticatedNexusRouteWithChildren
  '/_authenticated/nexus/alerts': typeof AuthenticatedNexusAlertsRoute
  '/_authenticated/nexus/approvals': typeof AuthenticatedNexusApprovalsRoute
  '/_authenticated/nexus/billing': typeof AuthenticatedNexusBillingRoute
  '/_authenticated/nexus/crm': typeof AuthenticatedNexusCrmRoute
  '/_authenticated/nexus/finance': typeof AuthenticatedNexusFinanceRoute
  '/_authenticated/nexus/hr': typeof AuthenticatedNexusHrRoute
  '/_authenticated/nexus/intelligence': typeof AuthenticatedNexusIntelligenceRoute
  '/_authenticated/nexus/mail-hub': typeof AuthenticatedNexusMailHubRoute
  '/_authenticated/nexus/monitoring': typeof AuthenticatedNexusMonitoringRoute
  '/_authenticated/nexus/observability': typeof AuthenticatedNexusObservabilityRoute
  '/_authenticated/nexus/operations': typeof AuthenticatedNexusOperationsRoute
  '/_authenticated/nexus/platform': typeof AuthenticatedNexusPlatformRoute
  '/_authenticated/nexus/production': typeof AuthenticatedNexusProductionRoute
  '/_authenticated/nexus/projects': typeof AuthenticatedNexusProjectsRouteWithChildren
  '/_authenticated/nexus/qa': typeof AuthenticatedNexusQaRoute
  '/_authenticated/nexus/quality': typeof AuthenticatedNexusQualityRoute
  '/_authenticated/nexus/recruiting': typeof AuthenticatedNexusRecruitingRoute
  '/_authenticated/nexus/recruiting-enterprise': typeof AuthenticatedNexusRecruitingEnterpriseRoute
  '/_authenticated/nexus/reports': typeof AuthenticatedNexusReportsRoute
  '/_authenticated/nexus/safety': typeof AuthenticatedNexusSafetyRoute
  '/_authenticated/nexus/security': typeof AuthenticatedNexusSecurityRoute
  '/_authenticated/nexus/security-center': typeof AuthenticatedNexusSecurityCenterRoute
  '/_authenticated/nexus/settings': typeof AuthenticatedNexusSettingsRoute
  '/_authenticated/nexus/supply': typeof AuthenticatedNexusSupplyRoute
  '/_authenticated/nexus/timeline': typeof AuthenticatedNexusTimelineRoute
  '/_authenticated/nexus/whatsapp-bridge': typeof AuthenticatedNexusWhatsappBridgeRoute
  '/_authenticated/nexus/': typeof AuthenticatedNexusIndexRoute
  '/_authenticated/nexus/projects/$projectId': typeof AuthenticatedNexusProjectsProjectIdRoute
  '/api/public/hooks/interview-reminders': typeof ApiPublicHooksInterviewRemindersRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-privacidad'
    | '/cookies'
    | '/cumplimiento'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/terminos'
    | '/nexus'
    | '/nexus/alerts'
    | '/nexus/approvals'
    | '/nexus/billing'
    | '/nexus/crm'
    | '/nexus/finance'
    | '/nexus/hr'
    | '/nexus/intelligence'
    | '/nexus/mail-hub'
    | '/nexus/monitoring'
    | '/nexus/observability'
    | '/nexus/operations'
    | '/nexus/platform'
    | '/nexus/production'
    | '/nexus/projects'
    | '/nexus/qa'
    | '/nexus/quality'
    | '/nexus/recruiting'
    | '/nexus/recruiting-enterprise'
    | '/nexus/reports'
    | '/nexus/safety'
    | '/nexus/security'
    | '/nexus/security-center'
    | '/nexus/settings'
    | '/nexus/supply'
    | '/nexus/timeline'
    | '/nexus/whatsapp-bridge'
    | '/nexus/'
    | '/nexus/projects/$projectId'
    | '/api/public/hooks/interview-reminders'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-privacidad'
    | '/cookies'
    | '/cumplimiento'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/terminos'
    | '/nexus/alerts'
    | '/nexus/approvals'
    | '/nexus/billing'
    | '/nexus/crm'
    | '/nexus/finance'
    | '/nexus/hr'
    | '/nexus/intelligence'
    | '/nexus/mail-hub'
    | '/nexus/monitoring'
    | '/nexus/observability'
    | '/nexus/operations'
    | '/nexus/platform'
    | '/nexus/production'
    | '/nexus/projects'
    | '/nexus/qa'
    | '/nexus/quality'
    | '/nexus/recruiting'
    | '/nexus/recruiting-enterprise'
    | '/nexus/reports'
    | '/nexus/safety'
    | '/nexus/security'
    | '/nexus/security-center'
    | '/nexus/settings'
    | '/nexus/supply'
    | '/nexus/timeline'
    | '/nexus/whatsapp-bridge'
    | '/nexus'
    | '/nexus/projects/$projectId'
    | '/api/public/hooks/interview-reminders'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aviso-privacidad'
    | '/cookies'
    | '/cumplimiento'
    | '/login'
    | '/registro'
    | '/reset-password'
    | '/terminos'
    | '/_authenticated/nexus'
    | '/_authenticated/nexus/alerts'
    | '/_authenticated/nexus/approvals'
    | '/_authenticated/nexus/billing'
    | '/_authenticated/nexus/crm'
    | '/_authenticated/nexus/finance'
    | '/_authenticated/nexus/hr'
    | '/_authenticated/nexus/intelligence'
    | '/_authenticated/nexus/mail-hub'
    | '/_authenticated/nexus/monitoring'
    | '/_authenticated/nexus/observability'
    | '/_authenticated/nexus/operations'
    | '/_authenticated/nexus/platform'
    | '/_authenticated/nexus/production'
    | '/_authenticated/nexus/projects'
    | '/_authenticated/nexus/qa'
    | '/_authenticated/nexus/quality'
    | '/_authenticated/nexus/recruiting'
    | '/_authenticated/nexus/recruiting-enterprise'
    | '/_authenticated/nexus/reports'
    | '/_authenticated/nexus/safety'
    | '/_authenticated/nexus/security'
    | '/_authenticated/nexus/security-center'
    | '/_authenticated/nexus/settings'
    | '/_authenticated/nexus/supply'
    | '/_authenticated/nexus/timeline'
    | '/_authenticated/nexus/whatsapp-bridge'
    | '/_authenticated/nexus/'
    | '/_authenticated/nexus/projects/$projectId'
    | '/api/public/hooks/interview-reminders'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AvisoPrivacidadRoute: typeof AvisoPrivacidadRoute
  CookiesRoute: typeof CookiesRoute
  CumplimientoRoute: typeof CumplimientoRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
  ApiPublicHooksInterviewRemindersRoute: typeof ApiPublicHooksInterviewRemindersRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-privacidad': {
      id: '/aviso-privacidad'
      path: '/aviso-privacidad'
      fullPath: '/aviso-privacidad'
      preLoaderRoute: typeof AvisoPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nexus': {
      id: '/_authenticated/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof AuthenticatedNexusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nexus/': {
      id: '/_authenticated/nexus/'
      path: '/'
      fullPath: '/nexus/'
      preLoaderRoute: typeof AuthenticatedNexusIndexRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/whatsapp-bridge': {
      id: '/_authenticated/nexus/whatsapp-bridge'
      path: '/whatsapp-bridge'
      fullPath: '/nexus/whatsapp-bridge'
      preLoaderRoute: typeof AuthenticatedNexusWhatsappBridgeRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/timeline': {
      id: '/_authenticated/nexus/timeline'
      path: '/timeline'
      fullPath: '/nexus/timeline'
      preLoaderRoute: typeof AuthenticatedNexusTimelineRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/supply': {
      id: '/_authenticated/nexus/supply'
      path: '/supply'
      fullPath: '/nexus/supply'
      preLoaderRoute: typeof AuthenticatedNexusSupplyRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/settings': {
      id: '/_authenticated/nexus/settings'
      path: '/settings'
      fullPath: '/nexus/settings'
      preLoaderRoute: typeof AuthenticatedNexusSettingsRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/security-center': {
      id: '/_authenticated/nexus/security-center'
      path: '/security-center'
      fullPath: '/nexus/security-center'
      preLoaderRoute: typeof AuthenticatedNexusSecurityCenterRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/security': {
      id: '/_authenticated/nexus/security'
      path: '/security'
      fullPath: '/nexus/security'
      preLoaderRoute: typeof AuthenticatedNexusSecurityRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/safety': {
      id: '/_authenticated/nexus/safety'
      path: '/safety'
      fullPath: '/nexus/safety'
      preLoaderRoute: typeof AuthenticatedNexusSafetyRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/reports': {
      id: '/_authenticated/nexus/reports'
      path: '/reports'
      fullPath: '/nexus/reports'
      preLoaderRoute: typeof AuthenticatedNexusReportsRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/recruiting-enterprise': {
      id: '/_authenticated/nexus/recruiting-enterprise'
      path: '/recruiting-enterprise'
      fullPath: '/nexus/recruiting-enterprise'
      preLoaderRoute: typeof AuthenticatedNexusRecruitingEnterpriseRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/recruiting': {
      id: '/_authenticated/nexus/recruiting'
      path: '/recruiting'
      fullPath: '/nexus/recruiting'
      preLoaderRoute: typeof AuthenticatedNexusRecruitingRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/quality': {
      id: '/_authenticated/nexus/quality'
      path: '/quality'
      fullPath: '/nexus/quality'
      preLoaderRoute: typeof AuthenticatedNexusQualityRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/qa': {
      id: '/_authenticated/nexus/qa'
      path: '/qa'
      fullPath: '/nexus/qa'
      preLoaderRoute: typeof AuthenticatedNexusQaRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/projects': {
      id: '/_authenticated/nexus/projects'
      path: '/projects'
      fullPath: '/nexus/projects'
      preLoaderRoute: typeof AuthenticatedNexusProjectsRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/production': {
      id: '/_authenticated/nexus/production'
      path: '/production'
      fullPath: '/nexus/production'
      preLoaderRoute: typeof AuthenticatedNexusProductionRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/platform': {
      id: '/_authenticated/nexus/platform'
      path: '/platform'
      fullPath: '/nexus/platform'
      preLoaderRoute: typeof AuthenticatedNexusPlatformRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/operations': {
      id: '/_authenticated/nexus/operations'
      path: '/operations'
      fullPath: '/nexus/operations'
      preLoaderRoute: typeof AuthenticatedNexusOperationsRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/observability': {
      id: '/_authenticated/nexus/observability'
      path: '/observability'
      fullPath: '/nexus/observability'
      preLoaderRoute: typeof AuthenticatedNexusObservabilityRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/monitoring': {
      id: '/_authenticated/nexus/monitoring'
      path: '/monitoring'
      fullPath: '/nexus/monitoring'
      preLoaderRoute: typeof AuthenticatedNexusMonitoringRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/mail-hub': {
      id: '/_authenticated/nexus/mail-hub'
      path: '/mail-hub'
      fullPath: '/nexus/mail-hub'
      preLoaderRoute: typeof AuthenticatedNexusMailHubRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/intelligence': {
      id: '/_authenticated/nexus/intelligence'
      path: '/intelligence'
      fullPath: '/nexus/intelligence'
      preLoaderRoute: typeof AuthenticatedNexusIntelligenceRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/hr': {
      id: '/_authenticated/nexus/hr'
      path: '/hr'
      fullPath: '/nexus/hr'
      preLoaderRoute: typeof AuthenticatedNexusHrRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/finance': {
      id: '/_authenticated/nexus/finance'
      path: '/finance'
      fullPath: '/nexus/finance'
      preLoaderRoute: typeof AuthenticatedNexusFinanceRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/crm': {
      id: '/_authenticated/nexus/crm'
      path: '/crm'
      fullPath: '/nexus/crm'
      preLoaderRoute: typeof AuthenticatedNexusCrmRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/billing': {
      id: '/_authenticated/nexus/billing'
      path: '/billing'
      fullPath: '/nexus/billing'
      preLoaderRoute: typeof AuthenticatedNexusBillingRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/approvals': {
      id: '/_authenticated/nexus/approvals'
      path: '/approvals'
      fullPath: '/nexus/approvals'
      preLoaderRoute: typeof AuthenticatedNexusApprovalsRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/_authenticated/nexus/alerts': {
      id: '/_authenticated/nexus/alerts'
      path: '/alerts'
      fullPath: '/nexus/alerts'
      preLoaderRoute: typeof AuthenticatedNexusAlertsRouteImport
      parentRoute: typeof AuthenticatedNexusRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/interview-reminders': {
      id: '/api/public/hooks/interview-reminders'
      path: '/api/public/hooks/interview-reminders'
      fullPath: '/api/public/hooks/interview-reminders'
      preLoaderRoute: typeof ApiPublicHooksInterviewRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nexus/projects/$projectId': {
      id: '/_authenticated/nexus/projects/$projectId'
      path: '/$projectId'
      fullPath: '/nexus/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedNexusProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedNexusProjectsRoute
    }
  }
}

interface AuthenticatedNexusProjectsRouteChildren {
  AuthenticatedNexusProjectsProjectIdRoute: typeof AuthenticatedNexusProjectsProjectIdRoute
}

const AuthenticatedNexusProjectsRouteChildren: AuthenticatedNexusProjectsRouteChildren =
  {
    AuthenticatedNexusProjectsProjectIdRoute:
      AuthenticatedNexusProjectsProjectIdRoute,
  }

const AuthenticatedNexusProjectsRouteWithChildren =
  AuthenticatedNexusProjectsRoute._addFileChildren(
    AuthenticatedNexusProjectsRouteChildren,
  )

interface AuthenticatedNexusRouteChildren {
  AuthenticatedNexusAlertsRoute: typeof AuthenticatedNexusAlertsRoute
  AuthenticatedNexusApprovalsRoute: typeof AuthenticatedNexusApprovalsRoute
  AuthenticatedNexusBillingRoute: typeof AuthenticatedNexusBillingRoute
  AuthenticatedNexusCrmRoute: typeof AuthenticatedNexusCrmRoute
  AuthenticatedNexusFinanceRoute: typeof AuthenticatedNexusFinanceRoute
  AuthenticatedNexusHrRoute: typeof AuthenticatedNexusHrRoute
  AuthenticatedNexusIntelligenceRoute: typeof AuthenticatedNexusIntelligenceRoute
  AuthenticatedNexusMailHubRoute: typeof AuthenticatedNexusMailHubRoute
  AuthenticatedNexusMonitoringRoute: typeof AuthenticatedNexusMonitoringRoute
  AuthenticatedNexusObservabilityRoute: typeof AuthenticatedNexusObservabilityRoute
  AuthenticatedNexusOperationsRoute: typeof AuthenticatedNexusOperationsRoute
  AuthenticatedNexusPlatformRoute: typeof AuthenticatedNexusPlatformRoute
  AuthenticatedNexusProductionRoute: typeof AuthenticatedNexusProductionRoute
  AuthenticatedNexusProjectsRoute: typeof AuthenticatedNexusProjectsRouteWithChildren
  AuthenticatedNexusQaRoute: typeof AuthenticatedNexusQaRoute
  AuthenticatedNexusQualityRoute: typeof AuthenticatedNexusQualityRoute
  AuthenticatedNexusRecruitingRoute: typeof AuthenticatedNexusRecruitingRoute
  AuthenticatedNexusRecruitingEnterpriseRoute: typeof AuthenticatedNexusRecruitingEnterpriseRoute
  AuthenticatedNexusReportsRoute: typeof AuthenticatedNexusReportsRoute
  AuthenticatedNexusSafetyRoute: typeof AuthenticatedNexusSafetyRoute
  AuthenticatedNexusSecurityRoute: typeof AuthenticatedNexusSecurityRoute
  AuthenticatedNexusSecurityCenterRoute: typeof AuthenticatedNexusSecurityCenterRoute
  AuthenticatedNexusSettingsRoute: typeof AuthenticatedNexusSettingsRoute
  AuthenticatedNexusSupplyRoute: typeof AuthenticatedNexusSupplyRoute
  AuthenticatedNexusTimelineRoute: typeof AuthenticatedNexusTimelineRoute
  AuthenticatedNexusWhatsappBridgeRoute: typeof AuthenticatedNexusWhatsappBridgeRoute
  AuthenticatedNexusIndexRoute: typeof AuthenticatedNexusIndexRoute
}

const AuthenticatedNexusRouteChildren: AuthenticatedNexusRouteChildren = {
  AuthenticatedNexusAlertsRoute: AuthenticatedNexusAlertsRoute,
  AuthenticatedNexusApprovalsRoute: AuthenticatedNexusApprovalsRoute,
  AuthenticatedNexusBillingRoute: AuthenticatedNexusBillingRoute,
  AuthenticatedNexusCrmRoute: AuthenticatedNexusCrmRoute,
  AuthenticatedNexusFinanceRoute: AuthenticatedNexusFinanceRoute,
  AuthenticatedNexusHrRoute: AuthenticatedNexusHrRoute,
  AuthenticatedNexusIntelligenceRoute: AuthenticatedNexusIntelligenceRoute,
  AuthenticatedNexusMailHubRoute: AuthenticatedNexusMailHubRoute,
  AuthenticatedNexusMonitoringRoute: AuthenticatedNexusMonitoringRoute,
  AuthenticatedNexusObservabilityRoute: AuthenticatedNexusObservabilityRoute,
  AuthenticatedNexusOperationsRoute: AuthenticatedNexusOperationsRoute,
  AuthenticatedNexusPlatformRoute: AuthenticatedNexusPlatformRoute,
  AuthenticatedNexusProductionRoute: AuthenticatedNexusProductionRoute,
  AuthenticatedNexusProjectsRoute: AuthenticatedNexusProjectsRouteWithChildren,
  AuthenticatedNexusQaRoute: AuthenticatedNexusQaRoute,
  AuthenticatedNexusQualityRoute: AuthenticatedNexusQualityRoute,
  AuthenticatedNexusRecruitingRoute: AuthenticatedNexusRecruitingRoute,
  AuthenticatedNexusRecruitingEnterpriseRoute:
    AuthenticatedNexusRecruitingEnterpriseRoute,
  AuthenticatedNexusReportsRoute: AuthenticatedNexusReportsRoute,
  AuthenticatedNexusSafetyRoute: AuthenticatedNexusSafetyRoute,
  AuthenticatedNexusSecurityRoute: AuthenticatedNexusSecurityRoute,
  AuthenticatedNexusSecurityCenterRoute: AuthenticatedNexusSecurityCenterRoute,
  AuthenticatedNexusSettingsRoute: AuthenticatedNexusSettingsRoute,
  AuthenticatedNexusSupplyRoute: AuthenticatedNexusSupplyRoute,
  AuthenticatedNexusTimelineRoute: AuthenticatedNexusTimelineRoute,
  AuthenticatedNexusWhatsappBridgeRoute: AuthenticatedNexusWhatsappBridgeRoute,
  AuthenticatedNexusIndexRoute: AuthenticatedNexusIndexRoute,
}

const AuthenticatedNexusRouteWithChildren =
  AuthenticatedNexusRoute._addFileChildren(AuthenticatedNexusRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedNexusRoute: typeof AuthenticatedNexusRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNexusRoute: AuthenticatedNexusRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AvisoPrivacidadRoute: AvisoPrivacidadRoute,
  CookiesRoute: CookiesRoute,
  CumplimientoRoute: CumplimientoRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
  ApiPublicHooksInterviewRemindersRoute: ApiPublicHooksInterviewRemindersRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
